### ISSUE TITLE
Can you add options to run FateZero with CPU only?

### ISSUE THREAD

**Issue by fengmao** [ChenyangQiQi/FateZero#11]
Hi there, my computer is very old and does not support cuda, can you guys add support options to run this project with CPU only, thanks.

**Comment by ChenyangQiQi** [comment]
You may edit the device variable [here](https://github.com/ChenyangQiQi/FateZero/blob/7148fa72e7eb28ca0fbfa5bc689182afbe61ad82/test_fatezero.py#L165).
