### ISSUE TITLE
evaluation metrics code

### ISSUE THREAD

**Issue by dlutzzw** [ChenyangQiQi/FateZero#16]
Hi,thanks for your good work, how can I reproduce the quality results in the paper, and where is the code for the evaluation Metrics?

**Comment by ChenyangQiQi** [comment]
@dlutzzw  Hi, thanks for your interest! You can first reproduce the video results using the existing config files! I will upload the evaluation metrics later (maybe in a week). I will tell you when I finish cleaning the evaluation code.

**Comment by dlutzzw** [comment]
thanks



---- Replied Message ----
| From | Chenyang ***@***.***> |
| Date | 06/28/2023 08:02 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [ChenyangQiQi/FateZero] evaluation metrics code (Issue #16) |

@dlutzzw Hi, thanks for your interest! You can first reproduce the video results using the existing config files! I will upload the evaluation metrics later (maybe in a week). I will tell you when I finish cleaning the evaluation code.

**Comment by ChenyangQiQi** [comment]
@dlutzzw Hi, the clip metrics are here https://github.com/ChenyangQiQi/FateZero/blob/main/CLIP/frame_acc_tem_con.py
