### ISSUE TITLE
Hand + Face of Human Pose

### ISSUE THREAD

**Issue by p0mad** [ChenyangQiQi/FateZero#18]
Hi,
Is it possible to generate a single character from the Pose for about 5 seconds?

I have a video of Pose ( openpose + hands + face) and i was wondering if it is possible to generate an output video withe the length of 5 seconds that has a consistent character/Avatar which plays Dance, .... from the controlled (pose) input?

I have a video of OpenPose+hands+face and i want to generate human like animation (No matter what, but just a consistent Character/Avatar)
[Sample Video](https://github.com/YBYBZhang/ControlVideo/assets/131435526/9062c944-270d-40c0-866b-b72455d58254)

Thanks
Best regards

**Comment by ChenyangQiQi** [comment]
Thanks for your interest.
I would recommend some works focus on  human pose generation ( https://github.com/mayuelala/FollowYourPose) or talking head generation (portrait.github.io), and using checkpoint finetuned on human ([anything](https://civitai.com/models/66/anything-v3)) 
Our framework focuses on open-domain text-driven generation and can be sub-optimal for your human generation task.
