### ISSUE TITLE
Strange Config Item.

### ISSUE THREAD

**Issue by guyuchao** [ChenyangQiQi/FateZero#19]
Hi, I found in jeep_posche.yaml, it has "watercolor, painiting, car", which don't present in the edited prompt.

`
eq_params: 
    words: ["watercolor", "painting"]
    values: [10,10]
blend_words: [['jeep',], ["car",]] 
blend_self_attention:  True
`

**Comment by mayuelala** [comment]
Hi, maybe you don't need to care about it, and you could delet it. It does not matter

**Comment by ChenyangQiQi** [comment]
@guyuchao. It is simply because I copy the template from "watercolor painting.yaml". These config will not work in the jeep_posche.yaml
