### ISSUE TITLE
What is the VRAM requirements of this video editing?

### ISSUE THREAD

**Issue by ninjasaid2k** [ChenyangQiQi/FateZero#2]
I'm not sure about the requirements of this video editor, Is it heavy on VRAM?

**Comment by meet1919** [comment]
24gb used for testing by the authors

**Comment by vinthony** [comment]
Hi, thanks for your attention, currently, we store all the attention in VRAM, thus, a larger VRAM(~100GB) might give full experience of our algorithm.

We are working to make it into google colab. We tried several configurations and found it might be ok(less texture than 50 steps) if we only use 10+ steps in DDIM inversion for stylized editing (just a simple experiment by changing `num_inference_steps` to 10 in `config/debugs/jeep_watercolor.yaml` ). Thus, 16G VRAM might be good enough for the style editing experiments and more examples will be tested.

Colab contains 12G VRAM ( we have tested changing `num_inference_steps` to 8, it works, but not good enough), we will plan to store the fused attentions in hardware to avoid heavy VRAM usage, more details will be coming soon.

**Comment by meet1919** [comment]
I tried first on colab but vram caused oom. Then I rented a RTX 3090 (24gb) on runpod and tried. The process gets killed everytime around 75%. Do you know why this should happen?

![Screenshot (251)](https://user-images.githubusercontent.com/62868163/226168509-98c18b5d-aa74-4c66-9178-9d3c995f9026.png)

**Comment by vinthony** [comment]
Hi, it seems the GPU is out of memory. Make sure you have the correct environment.

I try the following configuration. It works even in a 16GB GPU colab.

```
%pip install -q -U --pre triton
%pip install -q diffusers[torch]==0.11.1 transformers==4.26.0 bitsandbytes==0.35.4 \
decord accelerate omegaconf einops ftfy gradio imageio-ffmpeg xformers
```

Then, test via:
``` 
!accelerate launch test_fatezero.py --config=config/teaser/jeep_watercolor.yaml # --config=$CONFIG_NAME
```

**Comment by meet1919** [comment]
I have installed everything that was on `requirements.py` file. But I used !python instead of !accelerate

**Comment by meet1919** [comment]
running on colab `!accelerate launch test_fatezero.py --config=config/teaser/jeep_watercolor.yaml`

```
subprocess.CalledProcessError: Command '['/usr/bin/python3', 'test_fatezero.py', '--config=config/teaser/jeep_watercolor.yaml']' died with <Signals.SIGKILL: 9>.
```

`num_inference_steps` was set to `10`

**Comment by vinthony** [comment]
> running on colab `!accelerate launch test_fatezero.py --config=config/teaser/jeep_watercolor.yaml`
> 
> ```
> subprocess.CalledProcessError: Command '['/usr/bin/python3', 'test_fatezero.py', '--config=config/teaser/jeep_watercolor.yaml']' died with <Signals.SIGKILL: 9>.
> ```
> 
> `num_inference_steps` was set to `10`. I think ram in oom instead of vram

As I menthoed above, Colab contains 12G VRAM ( we have tested changing num_inference_steps to 8, it works, but not good enough)

**Comment by meet1919** [comment]
Yes, sorry I misread. I used `num_inference_steps` = `7` and it worked.
