### ISSUE TITLE
About "strength" in sd_ddim_pipeline function

### ISSUE THREAD

**Issue by Jason-user** [ChenyangQiQi/FateZero#20]
Hello, I put a description about the parameter "strength" below. My understanding is that if we designate "strength = 0.0," it implies the denoising of a clean image. Conversely, by setting "strength = 1.0," it suggests denoising from pure noise. However, I observed that even when I varied this parameter as 0.1, 0.5, and 1.0 respectively, the resulting outputs were identical. I'm just wondering where I can generate an output image purely from noise. Thank you for your assistance!
https://github.com/ChenyangQiQi/FateZero/blob/08da87636f673dc5b0a130713a2f6ee4de872e44/video_diffusion/pipelines/p2p_ddim_spatial_temporal.py#L295-L300

https://github.com/ChenyangQiQi/FateZero/blob/08da87636f673dc5b0a130713a2f6ee4de872e44/video_diffusion/pipelines/p2p_ddim_spatial_temporal.py#L261-L281

**Comment by mayuelala** [comment]
If you want to generate the result from pure noise, you could modify the ddim inversion to pure noise  [here](https://github.com/ChenyangQiQi/FateZero/blob/main/video_diffusion/pipelines/p2p_ddim_spatial_temporal.py#L370). similar with original stable diffusion pipline.

If you have any question about the code, please let me know. I will try my best to help you.
remember to give us a star if you like our work.

**Comment by ChenyangQiQi** [comment]
@Jason-user Sorry that I do not implement the "SDEdit"-style code about the "strength" that you mentioned. Maybe this variable won't influence the result.
However, a simple equivalent way to modify the strength without modifying code is to use the "latent blending" feature. (https://github.com/ChenyangQiQi/FateZero/blob/36aff9366ced0e9c2c083e451ba8eb9ea8fd0aa5/config/teaser/jeep_posche_local_latent_blend.yaml#L38)

If you replace the latent in the "0.5T" timestep. The final image result is the same as the denoising strengh= 0.5.
I share some results of our ablation study.
![image](https://github.com/ChenyangQiQi/FateZero/assets/45789244/6e4f1906-6621-44b7-8fb9-76450b11bb71)

But, if you want to save computation by smaller strengths, you may need to implement it by yourself.

**Comment by Jason-user** [comment]
@mayuelala @ChenyangQiQi Got it, thanks for you help!
