### ISSUE TITLE
Unable to reproduce jeep watercolor example in demos/paper

### ISSUE THREAD

**Issue by kkahatapitiya** [ChenyangQiQi/FateZero#22]
Thank you for the excellent codebase and really useful research contributions. I was trying to replicate the jeep watercolor example given in demos/paper using the same hyperparameters (jeep_watercolor.yaml), but seems a bit degraded compared to what’s reported. Can you verify these hyperparameters are correct in the yaml?

I am able to reproduce some other examples closely including jeep posche.

**Comment by ChenyangQiQi** [comment]
I run again. The result is correct on my 3090 GPU.
As you can reproduce the Porsche example, your code should be correct.
I am not sure what the problem is with your results, but I do observe some minor changes using different random seeds or image frames.
There is still randomness exist in the computation pipeline
![image](https://github.com/ChenyangQiQi/FateZero/assets/45789244/6fba1f95-9873-4a51-be60-c769d674f344)

**Comment by kkahatapitiya** [comment]
Thanks for your quick response.

I am running your code w/o any changes on a V100 gpu. I use the same hyperparameters as in [jeep_watercolor.yaml](https://github.com/ChenyangQiQi/FateZero/blob/main/config/style/jeep_watercolor.yaml). Below are the results I get. On the left I set the strength watercolor to be 3, instead of default 10 (shown to the right) as in the config file. As you see, the details are missing when using the default config (right).

![image](https://github.com/ChenyangQiQi/FateZero/assets/22514404/34eadfeb-1260-4097-97ea-283f48c48074)

Also, I see some differences in the image you posted above and the main result of the demo/paper ([here](https://fate-zero-edit.github.io/static/videos/2_car_watercolor_conat_result.mp4)). I understand that there is randomness in generation, but the change in details is high is these different versions. I am trying to get a faithful baseline to what's reported in the paper. I would highly appreciate if you can post the exact config file that you used to generate those results. Thanks in advance!

Again, great work and excellent repo!
