### ISSUE TITLE
Google colab error

### ISSUE THREAD

**Issue by lxycopper** [ChenyangQiQi/FateZero#25]
When I run this code block in Google Colab
`!accelerate launch test_fatezero.py --config=$CONFIG_NAME`
 it raises an error:

![image](https://github.com/ChenyangQiQi/FateZero/assets/52530394/34fd6dbf-6d54-48e7-8340-f2262d926d73)

**Comment by ChenyangQiQi** [comment]
Very weird. It seems the inversion part and editing part are both running correctly.
Is it because of out-of-memory or interrupted by Colab infrastructure?
You may also try to run it on your personal machine.
