### ISSUE TITLE
How to apply the original Tune-A-Video model on FateZero

### ISSUE THREAD

**Issue by ZhaochenYu0201** [ChenyangQiQi/FateZero#26]
I finetuned a model based on the Tune-A-Video architecture, and it could inference in the framework of the Tune-A-Video, but when i try to use the pre-trained Tune-A-Video on your code, it reports an error:
**KeyError: '2d state_dict key down_blocks.0.attentions.0.transformer_blocks.0.attn_temp.to_q.weight does not exist in 3d model'**
<img width="711" alt="image" src="https://github.com/ChenyangQiQi/FateZero/assets/115272494/e3bdd906-d80b-4e25-9b8e-b11a6963be92">
I wonder how to solve the problem, or do you make any changes on the original Tune-A-Video frame work?
Do you provide the code for fine-tuning a Tune-A-Video model which could be used in your framework?

**Comment by ChenyangQiQi** [comment]
Our namespace can be different from the latest official Tune-a-video, although their idea is the same

(1) Get a tune-a-video checkpoint using the code we provided (https://github.com/ChenyangQiQi/FateZero/blob/main/train_tune_a_video.py)
(2) Choose the official Tune-a-video training framework and write glue code to align the namespace
