### ISSUE TITLE
error

### ISSUE THREAD

**Issue by fuchao01** [ChenyangQiQi/FateZero#3]
python test_fatezero.py --config config/teaser/jeep_watercolor.yaml

The config attributes {'scaling_factor': 0.18215} were passed to AutoencoderKL, but are not expected and will be ignored. Please verify your config.json configuration file.
use fp16
down_blocks
Number of attention layer registered 32
 Invert clean image to noise latents by DDIM and Unet
 64%|████████████████████████████████████████████████████████▉                                | 32/50 [00:58<00:32,  1.79s/it]
Killed

NVIDIA-SMI 525.89.02    Driver Version: 525.89.02    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100-PCIE...  On   | 00000000:65:04.0 Off |                  Off |
| N/A   32C    P0    25W / 250W |      0MiB / 32768MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

**Comment by fuchao01** [comment]
我使用V100 32G VRAM，每次执行到30步左右的时候都会被kill，也不报其他的error

**Comment by vinthony** [comment]
你好，killed的原因是内存不足。 可能可以调低ddim步数，见 #2

**Comment by fuchao01** [comment]
我已经按#2 设置num_inference_steps = 7，但还是报错

**Comment by MaayanBogin** [comment]
> 我已经按#2 设置num_inference_steps = 7，但还是报错

我也有，但是还是不行

**Comment by meet1919** [comment]
> 我也有，但是还是不行

use `!accelerate` instead of `!pip`

**Comment by vinthony** [comment]
我们在A100上测试，使用accelerate库可以降低对于内存的需求。

```
accelerate launch test_fatezero.py --config=config/teaser/jeep_watercolor.yaml
```

**Comment by ChenyangQiQi** [comment]
Hi, you may try the following setting of fast style editing @MaayanBogin @meet1919 
For style and other easy editings, you could using 10 DDIM steps

accelerate launch test_fatezero.py --config config/fast_teaser/jeep_watercolor.yaml
On an Nvidia 3090 GPU, the above setting takes 10G GPU memory, 15G CPU memory, 10 seconds inversion per input video + 10 seconds editing per target prompt.
